Add component Footer dbox website angular
dboxjs/website pull request #14
Opened 2017-09-14 17:51 UTC by alexfuser

Coloque el footer en app.component.html mientras se decide si existirá un home

2017-09-14 22:28 UTC, jorandradefig requested changes
Tu PR no incluye el archivo `footer.component.pug`, por lo tanto tampoco incluye el arhivo .html.

Utiliza las Google Fonts para integrar la fuente Lato. @alexfuser

2017-09-14 22:28 UTC, jorandradefig commented on src/styles.styl
> +@font-face {
Google Fonts tiene en su catálogo la fuente [Lato](https://fonts.google.com/specimen/Lato). Usar esta mejor.

2017-09-14 22:54 UTC, jorandradefig commented
Este PR completa el issue #8.

2017-09-15 18:04 UTC, alexfuser commented
Listo, he cambiado y agregado el archivo pug y cambiado a font google Lato

2017-09-16 02:47 UTC, merged